const ROLES = {
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER'
}

const PERMISSIONS = {
  // Cursos
  CREATE_COURSE: 'CREATE_COURSE',
  EDIT_COURSE: 'EDIT_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  READ_COURSE: 'READ_COURSE',

  // Aulas (Classrooms)
  CREATE_CLASSROOM: 'CREATE_CLASSROOM',
  EDIT_CLASSROOM: 'EDIT_CLASSROOM',
  DELETE_CLASSROOM: 'DELETE_CLASSROOM',
  READ_CLASSROOM: 'READ_CLASSROOM',

  // Periodos académicos
  CREATE_PERIOD: 'CREATE_PERIOD',
  EDIT_PERIOD: 'EDIT_PERIOD',
  DELETE_PERIOD: 'DELETE_PERIOD',
  READ_PERIOD: 'READ_PERIOD',

  // Horarios
  CREATE_SCHEDULE: 'CREATE_SCHEDULE',
  EDIT_SCHEDULE: 'EDIT_SCHEDULE',
  DELETE_SCHEDULE: 'DELETE_SCHEDULE',
  READ_SCHEDULE: 'READ_SCHEDULE',

  // Inscripciones (Enrollment)
  CREATE_ENROLLMENT: 'CREATE_ENROLLMENT',
  CANCEL_ENROLLMENT: 'CANCEL_ENROLLMENT',
  READ_ENROLLMENT: 'READ_ENROLLMENT',

  // Calificaciones
  CREATE_GRADE: 'CREATE_GRADE',
  EDIT_GRADE: 'EDIT_GRADE',
  DELETE_GRADE: 'DELETE_GRADE',
  READ_GRADE: 'READ_GRADE'
}

export { ROLES, PERMISSIONS }
